CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_dialog_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_dialogMaxStates_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_dialogPhrase_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_dialogToState_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_message_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_phrasePair_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_settings_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_user_sequence START 1;
CREATE SEQUENCE IF NOT EXISTS lingvobot.lingvobot_userDialog_sequence START 1;
